---
title: "Data Science at Chico State"
subtitle: " -_Without data, you're just another person with an opinion._  W. Edwards Deming' "
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---

# What is the Data Science Initative (DSI) at Chico State? 

The DSI is an interdisciplinary community that provides support and training for Data Science to the Chico State Campus and community. 

<!--* Read more about our [mission](mission.html) here. -->
* Who are the [people](people.html) involved? 
* Read our [report](DSInterestSurveyAnalysis.pdf) on a Survey of Data Science Interest at Chico State. 
* Current Data Science related [courses](courses.html). 

# Spring 2017 Workshop Series - Friday 3-4:30pm Miriam Library

[Advertisement flyer](Data Science Initiative Workshop Flier.pdf)

#### 3/24/2017 - [Kick off session! / Getting started with R.](materials/2017-03-24.html)
* **Presenter:** Dr. Robin Donatello (MATH), Dr. Rick Hubbard (BSIS), Dr. Essia Hamouda (CSCI)
* **Location:** MLIB 045
* **Level:** No Experience needed. 
* **[RSVP Form](https://goo.gl/forms/czkWtAPN3eEMSxqk2)**  (Optional, but helpful)
* **Description:** 	Informational session about who we are, what we are doing, and how you 
can learn/contribute. Hands on introduction to R and R Studio. 


#### 4/7/2017 - Preparing Data for Analysis

* **Presenter:** Dr. Rick Hubbard
* **Location:** MLIB 442
* **Level:** No Experience needed. 
* **Description:** Got data need analysis? 80% of data analysis is cleaning the data, 
you can cut that time down by setting yourself up for success! Come learn how to reduce 
headaches by recording data in a manner that will allow for a smooth import into your 
analysis program of choice. 


#### 4/14/2017 - Exploring your data
* **Presenter:** Dr. Robin Donatello 
* **Location:** MLIB 442
* **Level:** Beginner/Novice R  
* **Description:** 	How to start to understand what information your data contains by 
creating tables, summary stats, creating basic visualizations. How to identify missing
data and discussion on how to handle missing values. 


#### 4/21/2017	- How to get help with R. 
* **Presenter:** Dr. Essia Hamouda 
* **Location:** MLIB 045
* **Level:** Beginner/Novice R  
* **Description:** 	


#### 4/28/2017	- Analyzing data using R
* **Presenter:** Dr. Robin Donatello (MATH)
* **Location:** MLIB 442
* **Level:** Beginner/Novice R  
* **Description:** 	Overview of functions used to perform various statistical analysis techniques.


#### 5/5/2017	- Visualizing your Data using ggplot2
* **Presenter:** Dr. Essia Hamouda 
* **Location:** MLIB 442
* **Level:** Beginner/Novice R  
* **Description:** 	


#### 5/12/2017 - Networking Event
* **Host:** Dr. Rick Hubbard
* **Location:** TBD





