---
title: "Preparing Data for Analysis"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---

# Logistics

* MLIB 442
* 3PM - 4:30M(+)
* Friday
* April 7, 2017

 
# Are Your Data Tidy? Or, untidy?
 
Before data can be modeled, analyzed or interpreted...

...data must be accessible in meaning-laden forms.
 
Annually, many Analysts around the globe report expending up to 80% of the effort and duration of an investigation in "wrangling" and "tidying" data into a "shape" that enables thoughtful, economical analysis. Does this sound like one of your projects?
 
## Data Science Initiative - Hands-on Workshop Series
 
As part of its _Hands-on Workshop Series_, the **Chico Data Science Initiative** is pleased to provide this practical and applied session. _Preparing Data for Analysis_ is designed to assist everyone that analyzes data succeed and avoid (and/or resolve) frustrating problems unfortunately inherent in many datasets.
 
The _Preparing Data for Analysis Workshop_ offers something for everyone...from the earliest of beginners to the most sophisticated Data Scientists. 
 
## Data Science Initiative: Learning, Doing and...Cookies!
 
In addition to a place in space and time where interesting people address and resolve challenging questions, the Data Science Initiative also has a reputation for three fabulous things:

* **Learning** (about data, modeling, analysis, interpretation, visualization, etc.);
* **Doing** (all the above plus mentoring and problem-resolution); and
* **Cookies** (considered self-evident).

# Workshop Content
 
In this fast-paced _Preparing Data for Analysis Workshop_, you'll learn techniques to succeed with&mdash;as well as avoid-or remedy&mdash;important considerations affecting many datasets; such as:

* Data Formatting ("Lexical"),
* Meaning ("Semantic"), and
* Structure ("Data Normalization").

Through practical exercises applied to each problem area (above), you'll learn how to create _Units-of-Analysis_ pertinent to your data and desired analysis.
 
**Don't Need to Know R**
 
**IMPORTANT NOTE:** Because "R" (see https://cran.r-project.org) is currently considered the world's leading Data Analytical & Computation Language, R is used as the basis for most Data Science Initiative Workshops. 
 
However-irrespective of use of the R language-this Workshop's concepts are transferrable to other computational environments, such as Python, SQL (to a degree) and-to a lesser degree-MS-Excel. **You do not need to know R** to participate or benefit from this Workshop--although familiarity with R will enable completion of the hands-on exercises.
 
## Prior Preparation
 
To obtain the greatest gain from your Workshop participation, please bring a (relatively) recent laptop with R (version 3.3.3, "Another Canoe", or later, is recommended) and RStudio (v1.1.136, or later, is recommended) installed and operational. 
 
The Workshop exercises are based on the `tidyverse` R Package (if possible, please have it installed prior to the Workshop-there are many YouTube videos and other online resources which explain how to install R packages). NOTE: On install, tidyverse will also install nearly two dozen dependent packages (_e.g.,_ tidyr, dplyr, lubridate, DBI, and ggplot2...to name but a few). Please anticipate a series of package installs accompanying installation of `tidyverse`.
 
# Questions? Comments?
 
Please contact the _Workshop_ leader directly:

Dr. Rick Hubbard  
College of Business - BIS-Dept  
rphubbard@csuchico.edu  


