---
title: "Introduction Session"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---

# Logistics

* **Date:** Friday March 24, 2017 
* **Time:** 3-4:30 pm
* **Location:** MLIB 045
* **RSVP:** https://goo.gl/forms/czkWtAPN3eEMSxqk2  (Optional, but helpful)


# Overview

In this kick off session we'll discuss what Data Science is, how the Data Science Initiative at Chico State is rising to meet the challenge of preparing and training a much needed computational science workforce, and how you can be a part of it. Then we'll explore who our Data Science community is using R. 

# Materials

* Introduction slides will be posted here after the event. 

* Program installation, setup, preferences [[HTML only]](2017-03-24_Intro_R_Overview.html) 
   **NOT COVERED DURING WORKSHOP**
   
* Hands on Introduction to R - Exploring the Data Science Community in Chico. 
    - [[Download R code]](2017-03-24_IntroR_whois_DS.R) to download the source code for today. 
        - Opened in a browser window? Try your other right. 
        - Mac? Two finger click. 
    - Save this file to an easy to find place. Desktops are nice. 
    - Browse your computer to this place, and double click to open the file in R Studio. 
        - Opening it from the browser window will fail at some point. Don't do this. 
        - You may need to specify to open in R Studio, not R directly. 

### R package requirements
This tutorial uses the following packages:
`ggplot2`, `googlesheets`, `magrittr`




